src/apps/image/urls.py
from django.urls import path

from apps.image.views import ImageCreateView, ImageDetailView, images_list, \
    image_like

app_name = 'images'

urlpatterns = [
    path('', images_list, name='list'),
    path('create/', ImageCreateView.as_view(), name='create'),
    path('detail/<slug:slug>/', ImageDetailView.as_view(), name='detail'),
    path('like/', image_like, name='like')
]

src/config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('registration/', include('apps.account.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),

    path('', lambda request: redirect(reverse_lazy('dashboard'))),
    path('dashboard/', include('apps.base.urls')),
    path('images/', include('apps.image.urls', namespace='images')),
    path('people/', include('apps.people.urls', namespace='people')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        path('__debug__/', include(debug_toolbar.urls))
    ]

src/apps/image/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='image')
    url = models.URLField(max_length=2000, unique=True)
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    description = models.TextField(null=True)
    image = models.ImageField(upload_to='image/%Y/%d/%m')
    created = models.DateTimeField(auto_now_add=True)
    user_likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='liked_images')

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=('-created',))
        ]

    def get_absolute_url(self):
        return reverse('images:detail', args=(self.slug,))

    def __str__(self) -> str:
        return self.title


@receiver(pre_save, sender=Image)
def set_slug_by_title(sender, instance: Image, *_, **__) -> None:
    if instance.slug is None:
        instance.slug = slugify(instance.title)

src/apps/image/forms.py
import logging

import requests
from django import forms
from django.conf import settings
from django.core.files.base import ContentFile
from django.utils.text import slugify

from apps.image.models import Image

lg = logging.getLogger(__name__)


class ImageCreateForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': 'description',
            'cols': 40,
            'rows': 10,
        }),
        required=False,
    )
    image_response = None

    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'title'}),
            'url': forms.TextInput(attrs={'placeholder': 'URL'}),
        }

    def save(self, commit=True):
        """
        1. Set slug and get upload_name.
        2. Set the image.
        """
        instance = super().save(commit=False)

        url = self.cleaned_data['url']

        instance.slug = file_name = slugify(instance.title)
        extension = url.rsplit('.', 1)[1].lower()
        upload_name = f'{file_name}.{extension}'

        instance.image.save(
            upload_name,
            ContentFile(self.image_response.content),
            save=False
        )

        if commit:
            instance.save()
        return instance

    def clean_url(self):
        """Check the url and request an image."""
        url = self.cleaned_data['url']
        extension = url.rsplit('.', 1)[1].lower()

        try:
            self.image_response = requests.get(url)
            if self.image_response.status_code != 200:
                raise requests.exceptions.ConnectionError
        except requests.exceptions.ConnectionError:
            raise forms.ValidationError('Enter a valid url')

        if extension not in settings.ALLOWED_IMAGE_EXTENSIONS:
            raise forms.ValidationError('Url isn\'t match.')
        else:
            return url

src/apps/image/views.py
import enum
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator, PageNotAnInteger
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.http import require_GET, require_POST
from django.views.generic import DetailView

from apps.image.forms import ImageCreateForm
from apps.image.models import Image
from apps.image.serializers import ImageUsersSerializer

lg = logging.getLogger(__name__)


class LikeAction(enum.StrEnum):
    LIKE = 'like'
    UNLIKE = 'unlike'


class ImageCreateView(LoginRequiredMixin, View):
    template_name = 'image/create.html'

    def get(self, request: WSGIRequest) -> HttpResponse:
        context = {
            'selected': 'images',
            'form': ImageCreateForm()
        }
        return render(request, self.template_name, context)

    def post(self, request: WSGIRequest) -> HttpResponse:
        if (form := ImageCreateForm(request.POST)).is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()
            messages.success(request, 'Image added successfully!')
            return redirect(image.get_absolute_url())
        else:
            context = {
                'selected': 'images',
                'form': form,
            }
            return render(request, self.template_name, context)


class ImageDetailView(LoginRequiredMixin, DetailView):
    model = Image
    template_name = 'image/detail.html'
    context_object_name = 'image'
    extra_context = {'selected': 'images'}

    def get_context_data(self, **kwargs):
        image = self.object

        if image.user_likes.contains(self.request.user):
            action = LikeAction.UNLIKE
        else:
            action = LikeAction.LIKE

        kwargs['action'] = action
        return super().get_context_data(**kwargs)


@login_required
@require_POST
def image_like(request: WSGIRequest) -> HttpResponse:
    image_id = request.POST.get('image_id')
    image = get_object_or_404(Image, id=image_id)

    action = request.POST.get('action')
    match action:
        case LikeAction.LIKE:
            image.user_likes.add(request.user)
            action = LikeAction.UNLIKE

        case LikeAction.UNLIKE:
            image.user_likes.remove(request.user)
            action = LikeAction.LIKE

    image_serializer = ImageUsersSerializer(image.user_likes.all(),
                                            many=True)
    return JsonResponse({
        'action': action,
        'counter': image.user_likes.count(),
        'user_likes': image_serializer.data,
    })


@login_required
@require_GET
def images_list(request: WSGIRequest) -> HttpResponse:
    images = Image.objects.all()
    paginator = Paginator(images, 8)

    page = request.GET.get('page')
    images_only = request.GET.get('images_only')

    if images_only and int(page) > paginator.num_pages:
        return HttpResponse('')

    try:
        images = paginator.get_page(page)
    except PageNotAnInteger:
        images = paginator.get_page(1)

    if images_only:
        context = {'images': images}
        return render(request, 'image/list_images.html', context)
    else:
        context = {
            'images': images,
            'selected': 'images',
        }
        return render(request, 'image/list.html', context)

src/apps/image/templates/image/create.html
{% extends 'base.html' %}

{% block title %}Images{% endblock %}

{% block main %}
    <h1>Bookmark an image.</h1>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>{{ field }}{{ field.errors }}</p>
        {% endfor %}
        <button type="submit">Bookmark it!</button>
    </form>
{% endblock %}

src/apps/image/templates/image/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}

{% block main %}
    <h1>Bookmark an image.</h1>
    <h4>
        likes
        <span class="counter">{{ image.user_likes.count }}</span>
    </h4>
    <a href="{{ image.image.url }}">
        <img src="{% thumbnail image.image 0x800 %}" alt="" />
    </a>
    <form method="POST" class="like-form">
        {% csrf_token %}
        <button class="like-button">{{ action }}</button>
    </form>
    <div class="user_likes">
        {% for like_user in image.user_likes.all %}
            <h4>{{ like_user.username }}</h4>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', _ => {
            const like_form = document.querySelector('.like-form')
            const like_button = document.querySelector("button[class='like-button']")
            const counter = document.querySelector('.counter')
            const user_likes = document.querySelector('.user_likes')
            const url = "{% url 'images:like' %}"
            const csrf_token_input = document.querySelector("input[name='csrfmiddlewaretoken']")
            const csrf_token = csrf_token_input ? csrf_token_input.value : null

            like_form.onsubmit = (e) => {
                e.preventDefault()
                const action = like_button.innerText

                const form = new FormData()
                form.append('image_id', '{{ image.id }}')
                form.append('action', action)

                const headers = {
                    'X-CSRFToken': csrf_token,
                    'Content-Type': `multipart/form-data;
                     boundary=${form._boundary}`,
                }
                async function send_post() {
                    const response = await axios.post(url, form, {headers})
                    like_button.innerText = response.data.action
                    counter.innerText = response.data.counter


                    user_likes.innerHTML = response.data.user_likes.map(
                        user => `<h4>${user.username}</h4>`
                    )
                }
                send_post()
            }})
    </script>
{% endblock %}

src/apps/image/templates/image/list.html
{% extends 'base.html' %}

{% block title %}Images{% endblock %}

{% block main %}
    {% with images.count as total_count %}
        <h2>
            Image{{ total_count|pluralize }} ({{ total_count }}) |
            <a href="{% url 'images:create' %}">create image</a>
        </h2>
    {% endwith %}
    <div class="images">
        {% include 'image/list_images.html' %}
    </div>
{% endblock %}

{% block script %}
    <script>
        const image_list = document.querySelector('.images')
        let page = 1
        let empty_page = false
        let block_request = false

        document.addEventListener('scroll', _ => {
            const indent = 200
            const margin = document.body.clientHeight - window.innerHeight - indent

            if (window.pageYOffset > margin && !empty_page && !block_request) {
                console.log(`scroll ${page}`)
                block_request = true
                page++

                async function append_html() {
                    const response = await axios.get(`?images_only=true&page=${page}`)
                    const html = response.data

                    if (html === '') empty_page = true
                    else {
                        block_request = false
                        image_list.insertAdjacentHTML('beforeend', html)
                    }
                }
                append_html()
            }
        })
        const scroll_event = new Event('scroll')
        window.dispatchEvent(scroll_event)
    </script>
{% endblock %}

src/apps/image/templates/image/list_images.html
{% load thumbnail %}
{% for image in images %}
    <article class="image">
        <div class="info">
            <h3>
                <a href="{{ image.get_absolute_url }}">
                    {{ image.title }}
                </a>
            </h3>
        </div>
        <div class="photo">
           <a href="{{ image.get_absolute_url }}">
                <img src="{% thumbnail image.image 440x440 crop="smart" %}"
                     alt="" />
            </a>
        </div>
    </article>
{% endfor %}