src/apps/base/urls.py
from django.urls import path

from apps.base import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

src/apps/image/urls.py
from django.urls import path

from apps.image.views import ImageCreateView, ImageDetailView, images_list, \
    image_like

app_name = 'images'

urlpatterns = [
    path('', images_list, name='list'),
    path('create/', ImageCreateView.as_view(), name='create'),
    path('detail/<slug:slug>/', ImageDetailView.as_view(), name='detail'),
    path('like/', image_like, name='like')
]

src/config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('registration/', include('apps.account.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),

    path('', lambda request: redirect(reverse_lazy('dashboard'))),
    path('dashboard/', include('apps.base.urls')),
    path('images/', include('apps.image.urls', namespace='images')),
    path('people/', include('apps.people.urls', namespace='people')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        path('__debug__/', include(debug_toolbar.urls))
    ]

src/apps/base/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render


def dashboard(request: WSGIRequest) -> HttpResponse:
    template_name = 'base/dashboard.html'
    context = {'selected': 'dashboard'}
    return render(request, template_name, context)

src/apps/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <style>.image {display: inline-block;}</style>
</head>
<body>
    {% with request.user as user %}
        <header id="header">
            <span class="logo">
                <a href="{% url 'dashboard' %}">Bookmarks</a>
            </span>
            <nav class="menu">
                <span {% if selected == 'dashboard' %}class="selected"{% endif %}>
                    <a href="{% url 'dashboard' %}">dashboard</a>
                </span>
                <span {% if selected == 'images' %}class="selected"{% endif %}>
                    <a href="{% url 'images:list' %}">images</a>
                </span>
                <span {% if selected == 'people' %}class="selected"{% endif %}>
                    <a href="{% url 'people:list' %}">people</a>
                </span>
            </nav>
                {% if user.is_authenticated %}
                    <span class="user">
                        <span class="user__name">
                            {{ user.first_name|default:user.username }}
                        </span>
                        <span>
                            <a href="{% url 'password_change' %}">
                                change password
                            </a>
                        </span>
                        <span>
                            <a href="{% url 'logout' %}">logout</a>
                        </span>
                    </span>
                {% else %}
                    <span class="user">
                        <a href="{% url 'register' %}">register</a>
                        <a href="{% url 'login' %}">login</a>
                    </span>
                {% endif %}
        </header>
    {% endwith %}

    <main id="main">
        {% block main %}
        {% endblock %}
    </main>

    <script src="{% static 'js/get_cookies.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>